// "use client";

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "../components/Sidebar";
// import CommandBar from "../components/CommandBar";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;}>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CommandBar />
//         <div className="flex">
//           <Sidebar />
//           <main className="flex-1">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }


import { ReactNode } from "react";

type RootLayoutProps = {
  children: ReactNode;
};

import { Inter } from "next/font/google";
import Sidebar from "../components/Sidebar";
import CommandBar from "../components/CommandBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en">
    <body className={inter.className}>
      <Sidebar />
      <CommandBar />
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;